-- Logs begin at Mon 2021-06-28 13:35:09 UTC, end at Tue 2021-06-29 15:37:10 UTC. --
Jun 28 21:35:40 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: [2021-06-28 21:35:41 +0000] [7308] [INFO] Starting gunicorn 20.1.0
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: [2021-06-28 21:35:41 +0000] [7308] [INFO] Listening at: http://127.0.0.1:5000 (7308)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: [2021-06-28 21:35:41 +0000] [7308] [INFO] Using worker: sync
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: [2021-06-28 21:35:41 +0000] [7311] [INFO] Booting worker with pid: 7311
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: [2021-06-28 21:35:41 +0000] [7311] [ERROR] Exception in worker process
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: Traceback (most recent call last):
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:     worker.init_process()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:     self.load_wsgi()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:     self.wsgi = self.app.wsgi()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:     self.callable = self.load()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:     return self.load_wsgiapp()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:     return util.import_app(self.app_uri)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:     mod = importlib.import_module(module)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: ModuleNotFoundError: No module named 'wsgi'
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: [2021-06-28 21:35:41 +0000] [7311] [INFO] Worker exiting (pid: 7311)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: [2021-06-28 21:35:41 +0000] [7308] [INFO] Shutting down: Master
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7308]: [2021-06-28 21:35:41 +0000] [7308] [INFO] Reason: Worker failed to boot.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 1.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: [2021-06-28 21:35:41 +0000] [7313] [INFO] Starting gunicorn 20.1.0
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: [2021-06-28 21:35:41 +0000] [7313] [INFO] Listening at: http://127.0.0.1:5000 (7313)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: [2021-06-28 21:35:41 +0000] [7313] [INFO] Using worker: sync
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: [2021-06-28 21:35:41 +0000] [7316] [INFO] Booting worker with pid: 7316
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: [2021-06-28 21:35:41 +0000] [7316] [ERROR] Exception in worker process
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: Traceback (most recent call last):
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:     worker.init_process()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:     self.load_wsgi()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:     self.wsgi = self.app.wsgi()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:     self.callable = self.load()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:     return self.load_wsgiapp()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:     return util.import_app(self.app_uri)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:     mod = importlib.import_module(module)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: ModuleNotFoundError: No module named 'wsgi'
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: [2021-06-28 21:35:41 +0000] [7316] [INFO] Worker exiting (pid: 7316)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: [2021-06-28 21:35:41 +0000] [7313] [INFO] Shutting down: Master
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7313]: [2021-06-28 21:35:41 +0000] [7313] [INFO] Reason: Worker failed to boot.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 2.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: [2021-06-28 21:35:41 +0000] [7318] [INFO] Starting gunicorn 20.1.0
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: [2021-06-28 21:35:41 +0000] [7318] [INFO] Listening at: http://127.0.0.1:5000 (7318)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: [2021-06-28 21:35:41 +0000] [7318] [INFO] Using worker: sync
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: [2021-06-28 21:35:41 +0000] [7321] [INFO] Booting worker with pid: 7321
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: [2021-06-28 21:35:41 +0000] [7321] [ERROR] Exception in worker process
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: Traceback (most recent call last):
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:     worker.init_process()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:     self.load_wsgi()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:     self.wsgi = self.app.wsgi()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:     self.callable = self.load()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:     return self.load_wsgiapp()
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:     return util.import_app(self.app_uri)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:     mod = importlib.import_module(module)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: ModuleNotFoundError: No module named 'wsgi'
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: [2021-06-28 21:35:41 +0000] [7321] [INFO] Worker exiting (pid: 7321)
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: [2021-06-28 21:35:41 +0000] [7318] [INFO] Shutting down: Master
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal bash[7318]: [2021-06-28 21:35:41 +0000] [7318] [INFO] Reason: Worker failed to boot.
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 28 21:35:41 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 3.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: [2021-06-28 21:35:42 +0000] [7323] [INFO] Starting gunicorn 20.1.0
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: [2021-06-28 21:35:42 +0000] [7323] [INFO] Listening at: http://127.0.0.1:5000 (7323)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: [2021-06-28 21:35:42 +0000] [7323] [INFO] Using worker: sync
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: [2021-06-28 21:35:42 +0000] [7326] [INFO] Booting worker with pid: 7326
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: [2021-06-28 21:35:42 +0000] [7326] [ERROR] Exception in worker process
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: Traceback (most recent call last):
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:     worker.init_process()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:     self.load_wsgi()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:     self.wsgi = self.app.wsgi()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:     self.callable = self.load()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:     return self.load_wsgiapp()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:     return util.import_app(self.app_uri)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:     mod = importlib.import_module(module)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: ModuleNotFoundError: No module named 'wsgi'
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: [2021-06-28 21:35:42 +0000] [7326] [INFO] Worker exiting (pid: 7326)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: [2021-06-28 21:35:42 +0000] [7323] [INFO] Shutting down: Master
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7323]: [2021-06-28 21:35:42 +0000] [7323] [INFO] Reason: Worker failed to boot.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 4.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7328] [INFO] Starting gunicorn 20.1.0
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7328] [INFO] Listening at: http://127.0.0.1:5000 (7328)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7328] [INFO] Using worker: sync
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7331] [INFO] Booting worker with pid: 7331
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7331] [ERROR] Exception in worker process
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: Traceback (most recent call last):
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     worker.init_process()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     self.load_wsgi()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     self.wsgi = self.app.wsgi()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     self.callable = self.load()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     return self.load_wsgiapp()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     return util.import_app(self.app_uri)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     mod = importlib.import_module(module)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: ModuleNotFoundError: No module named 'wsgi'
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7331] [INFO] Worker exiting (pid: 7331)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7332] [INFO] Booting worker with pid: 7332
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7332] [ERROR] Exception in worker process
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: Traceback (most recent call last):
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     worker.init_process()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     self.load_wsgi()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     self.wsgi = self.app.wsgi()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     self.callable = self.load()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     return self.load_wsgiapp()
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     return util.import_app(self.app_uri)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     mod = importlib.import_module(module)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: ModuleNotFoundError: No module named 'wsgi'
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7332] [INFO] Worker exiting (pid: 7332)
Jun 28 21:35:42 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:42 +0000] [7328] [WARNING] Worker with pid 7332 was terminated due to signal 15
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:43 +0000] [7328] [INFO] Shutting down: Master
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal bash[7328]: [2021-06-28 21:35:43 +0000] [7328] [INFO] Reason: Worker failed to boot.
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 5.
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Start request repeated too quickly.
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 28 21:35:43 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Failed to start Gunicorn instance to serve my portfolio.
Jun 29 15:09:09 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: [2021-06-29 15:09:10 +0000] [19008] [INFO] Starting gunicorn 20.1.0
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: [2021-06-29 15:09:10 +0000] [19008] [INFO] Listening at: http://127.0.0.1:5000 (19008)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: [2021-06-29 15:09:10 +0000] [19008] [INFO] Using worker: sync
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: [2021-06-29 15:09:10 +0000] [19011] [INFO] Booting worker with pid: 19011
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: [2021-06-29 15:09:10 +0000] [19011] [ERROR] Exception in worker process
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: Traceback (most recent call last):
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:     worker.init_process()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:     self.load_wsgi()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:     self.wsgi = self.app.wsgi()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:     self.callable = self.load()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:     return self.load_wsgiapp()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:     return util.import_app(self.app_uri)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:     mod = importlib.import_module(module)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: [2021-06-29 15:09:10 +0000] [19011] [INFO] Worker exiting (pid: 19011)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: [2021-06-29 15:09:10 +0000] [19008] [INFO] Shutting down: Master
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19008]: [2021-06-29 15:09:10 +0000] [19008] [INFO] Reason: Worker failed to boot.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 1.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: [2021-06-29 15:09:10 +0000] [19013] [INFO] Starting gunicorn 20.1.0
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: [2021-06-29 15:09:10 +0000] [19013] [INFO] Listening at: http://127.0.0.1:5000 (19013)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: [2021-06-29 15:09:10 +0000] [19013] [INFO] Using worker: sync
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: [2021-06-29 15:09:10 +0000] [19016] [INFO] Booting worker with pid: 19016
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: [2021-06-29 15:09:10 +0000] [19016] [ERROR] Exception in worker process
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: Traceback (most recent call last):
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:     worker.init_process()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:     self.load_wsgi()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:     self.wsgi = self.app.wsgi()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:     self.callable = self.load()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:     return self.load_wsgiapp()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:     return util.import_app(self.app_uri)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:     mod = importlib.import_module(module)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: [2021-06-29 15:09:10 +0000] [19016] [INFO] Worker exiting (pid: 19016)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: [2021-06-29 15:09:10 +0000] [19013] [INFO] Shutting down: Master
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19013]: [2021-06-29 15:09:10 +0000] [19013] [INFO] Reason: Worker failed to boot.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 2.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: [2021-06-29 15:09:10 +0000] [19018] [INFO] Starting gunicorn 20.1.0
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: [2021-06-29 15:09:10 +0000] [19018] [INFO] Listening at: http://127.0.0.1:5000 (19018)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: [2021-06-29 15:09:10 +0000] [19018] [INFO] Using worker: sync
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: [2021-06-29 15:09:10 +0000] [19021] [INFO] Booting worker with pid: 19021
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: [2021-06-29 15:09:10 +0000] [19021] [ERROR] Exception in worker process
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: Traceback (most recent call last):
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:     worker.init_process()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:     self.load_wsgi()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:     self.wsgi = self.app.wsgi()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:     self.callable = self.load()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:     return self.load_wsgiapp()
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:     return util.import_app(self.app_uri)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:     mod = importlib.import_module(module)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:09:10 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: [2021-06-29 15:09:10 +0000] [19021] [INFO] Worker exiting (pid: 19021)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: [2021-06-29 15:09:11 +0000] [19018] [INFO] Shutting down: Master
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19018]: [2021-06-29 15:09:11 +0000] [19018] [INFO] Reason: Worker failed to boot.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 3.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: [2021-06-29 15:09:11 +0000] [19023] [INFO] Starting gunicorn 20.1.0
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: [2021-06-29 15:09:11 +0000] [19023] [INFO] Listening at: http://127.0.0.1:5000 (19023)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: [2021-06-29 15:09:11 +0000] [19023] [INFO] Using worker: sync
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: [2021-06-29 15:09:11 +0000] [19026] [INFO] Booting worker with pid: 19026
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: [2021-06-29 15:09:11 +0000] [19026] [ERROR] Exception in worker process
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: Traceback (most recent call last):
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:     worker.init_process()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:     self.load_wsgi()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:     self.wsgi = self.app.wsgi()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:     self.callable = self.load()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:     return self.load_wsgiapp()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:     return util.import_app(self.app_uri)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:     mod = importlib.import_module(module)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: [2021-06-29 15:09:11 +0000] [19026] [INFO] Worker exiting (pid: 19026)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: [2021-06-29 15:09:11 +0000] [19023] [INFO] Shutting down: Master
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19023]: [2021-06-29 15:09:11 +0000] [19023] [INFO] Reason: Worker failed to boot.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 4.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: [2021-06-29 15:09:11 +0000] [19028] [INFO] Starting gunicorn 20.1.0
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: [2021-06-29 15:09:11 +0000] [19028] [INFO] Listening at: http://127.0.0.1:5000 (19028)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: [2021-06-29 15:09:11 +0000] [19028] [INFO] Using worker: sync
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: [2021-06-29 15:09:11 +0000] [19031] [INFO] Booting worker with pid: 19031
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: [2021-06-29 15:09:11 +0000] [19031] [ERROR] Exception in worker process
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: Traceback (most recent call last):
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:     worker.init_process()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:     self.load_wsgi()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:     self.wsgi = self.app.wsgi()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:     self.callable = self.load()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:     return self.load_wsgiapp()
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:     return util.import_app(self.app_uri)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:     mod = importlib.import_module(module)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: [2021-06-29 15:09:11 +0000] [19031] [INFO] Worker exiting (pid: 19031)
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: [2021-06-29 15:09:11 +0000] [19028] [INFO] Shutting down: Master
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal bash[19028]: [2021-06-29 15:09:11 +0000] [19028] [INFO] Reason: Worker failed to boot.
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:09:11 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:09:12 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:09:12 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 5.
Jun 29 15:09:12 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:09:12 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Start request repeated too quickly.
Jun 29 15:09:12 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:09:12 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Failed to start Gunicorn instance to serve my portfolio.
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: [2021-06-29 15:36:54 +0000] [19781] [INFO] Starting gunicorn 20.1.0
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: [2021-06-29 15:36:54 +0000] [19781] [INFO] Listening at: http://127.0.0.1:5000 (19781)
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: [2021-06-29 15:36:54 +0000] [19781] [INFO] Using worker: sync
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: [2021-06-29 15:36:54 +0000] [19784] [INFO] Booting worker with pid: 19784
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: [2021-06-29 15:36:54 +0000] [19784] [ERROR] Exception in worker process
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: Traceback (most recent call last):
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:     worker.init_process()
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:     self.load_wsgi()
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:     self.wsgi = self.app.wsgi()
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:     self.callable = self.load()
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:     return self.load_wsgiapp()
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:     return util.import_app(self.app_uri)
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:     mod = importlib.import_module(module)
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: [2021-06-29 15:36:54 +0000] [19784] [INFO] Worker exiting (pid: 19784)
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: [2021-06-29 15:36:54 +0000] [19781] [INFO] Shutting down: Master
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal bash[19781]: [2021-06-29 15:36:54 +0000] [19781] [INFO] Reason: Worker failed to boot.
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:36:54 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 1.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: [2021-06-29 15:36:55 +0000] [19786] [INFO] Starting gunicorn 20.1.0
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: [2021-06-29 15:36:55 +0000] [19786] [INFO] Listening at: http://127.0.0.1:5000 (19786)
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: [2021-06-29 15:36:55 +0000] [19786] [INFO] Using worker: sync
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: [2021-06-29 15:36:55 +0000] [19791] [INFO] Booting worker with pid: 19791
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: [2021-06-29 15:36:55 +0000] [19791] [ERROR] Exception in worker process
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: Traceback (most recent call last):
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:     worker.init_process()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:     self.load_wsgi()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:     self.wsgi = self.app.wsgi()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:     self.callable = self.load()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:     return self.load_wsgiapp()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:     return util.import_app(self.app_uri)
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:     mod = importlib.import_module(module)
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: [2021-06-29 15:36:55 +0000] [19791] [INFO] Worker exiting (pid: 19791)
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: [2021-06-29 15:36:55 +0000] [19786] [INFO] Shutting down: Master
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19786]: [2021-06-29 15:36:55 +0000] [19786] [INFO] Reason: Worker failed to boot.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 2.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: [2021-06-29 15:36:55 +0000] [19793] [INFO] Starting gunicorn 20.1.0
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: [2021-06-29 15:36:55 +0000] [19793] [INFO] Listening at: http://127.0.0.1:5000 (19793)
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: [2021-06-29 15:36:55 +0000] [19793] [INFO] Using worker: sync
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: [2021-06-29 15:36:55 +0000] [19796] [INFO] Booting worker with pid: 19796
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: [2021-06-29 15:36:55 +0000] [19796] [ERROR] Exception in worker process
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: Traceback (most recent call last):
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:     worker.init_process()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:     self.load_wsgi()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:     self.wsgi = self.app.wsgi()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:     self.callable = self.load()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:     return self.load_wsgiapp()
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:     return util.import_app(self.app_uri)
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:     mod = importlib.import_module(module)
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:36:55 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: [2021-06-29 15:36:55 +0000] [19796] [INFO] Worker exiting (pid: 19796)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: [2021-06-29 15:36:56 +0000] [19793] [INFO] Shutting down: Master
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19793]: [2021-06-29 15:36:56 +0000] [19793] [INFO] Reason: Worker failed to boot.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 3.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: [2021-06-29 15:36:56 +0000] [19798] [INFO] Starting gunicorn 20.1.0
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: [2021-06-29 15:36:56 +0000] [19798] [INFO] Listening at: http://127.0.0.1:5000 (19798)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: [2021-06-29 15:36:56 +0000] [19798] [INFO] Using worker: sync
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: [2021-06-29 15:36:56 +0000] [19801] [INFO] Booting worker with pid: 19801
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: [2021-06-29 15:36:56 +0000] [19801] [ERROR] Exception in worker process
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: Traceback (most recent call last):
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:     worker.init_process()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:     self.load_wsgi()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:     self.wsgi = self.app.wsgi()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:     self.callable = self.load()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:     return self.load_wsgiapp()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:     return util.import_app(self.app_uri)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:     mod = importlib.import_module(module)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: [2021-06-29 15:36:56 +0000] [19801] [INFO] Worker exiting (pid: 19801)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: [2021-06-29 15:36:56 +0000] [19798] [INFO] Shutting down: Master
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19798]: [2021-06-29 15:36:56 +0000] [19798] [INFO] Reason: Worker failed to boot.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 4.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Started Gunicorn instance to serve my portfolio.
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: [2021-06-29 15:36:56 +0000] [19803] [INFO] Starting gunicorn 20.1.0
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: [2021-06-29 15:36:56 +0000] [19803] [INFO] Listening at: http://127.0.0.1:5000 (19803)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: [2021-06-29 15:36:56 +0000] [19803] [INFO] Using worker: sync
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: [2021-06-29 15:36:56 +0000] [19806] [INFO] Booting worker with pid: 19806
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: [2021-06-29 15:36:56 +0000] [19806] [ERROR] Exception in worker process
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: Traceback (most recent call last):
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:     worker.init_process()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:     self.load_wsgi()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:     self.wsgi = self.app.wsgi()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:     self.callable = self.load()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:     return self.load_wsgiapp()
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:     return util.import_app(self.app_uri)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "/home/centos/flask-blog/python3-virtualenv/lib64/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:     mod = importlib.import_module(module)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: ModuleNotFoundError: No module named 'wsgi'
Jun 29 15:36:56 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: [2021-06-29 15:36:56 +0000] [19806] [INFO] Worker exiting (pid: 19806)
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: [2021-06-29 15:36:57 +0000] [19803] [INFO] Shutting down: Master
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal bash[19803]: [2021-06-29 15:36:57 +0000] [19803] [INFO] Reason: Worker failed to boot.
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Service RestartSec=100ms expired, scheduling restart.
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Scheduled restart job, restart counter is at 5.
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Stopped Gunicorn instance to serve my portfolio.
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Start request repeated too quickly.
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: myportfolio.service: Failed with result 'exit-code'.
Jun 29 15:36:57 ip-172-31-33-210.us-east-2.compute.internal systemd[1]: Failed to start Gunicorn instance to serve my portfolio.
